
query article($id: String!) {
	article(id:$id) {
		id 
		title 
		isPublished
		thumbnail
		description
		content

	}
}

query articles($userId: String!) {
	articles(userId:$userId) {
		id 
		title
		thumbnail
		description
		isPublished
		content
	}
}
